Pages/Checkout.cshtml.cs
using Itec245_Final.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Itec245_Final.Pages
{
    [Authorize(Roles ="User, Admin")]
    public class CheckoutModel : PageModel
    {
        private readonly Itec245_Final.Data.ApplicationDbContext _context;

        public OrderHistory o = new OrderHistory();
        public CheckoutModel(Itec245_Final.Data.ApplicationDbContext context)
        {
            _context = context;
        }
        public IList<Shoes> Shoes { get; set; } = default!;
        public void OnGet()
        {

        }

        public void OnPostRemoveCustom(int myvalue)
        {
            HelperModel h = new HelperModel();


            h.remove(User.Identity.Name, _context, myvalue);
            Shoes = _context.shoes.ToList();
        }

        public void OnPostAddCustom(int myvalue)
        {
            HelperModel h = new HelperModel();


            h.AddShoes(User.Identity.Name, _context, myvalue);
            Shoes = _context.shoes.ToList();
        }

        public void OnpostFinal()
        {
           
            Page();
            HelperModel h = new HelperModel();
            h.CheckOut(User.Identity.Name, _context);
            Response.Redirect("Thank");

        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Itec245_Final.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Itec245_Final.Models;
using Itec245_Final.Pages.BrandsSort;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Itec245_Final.Pages
{
    [Authorize(Roles = "User,Admin")]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            //var cart = CartHolder.GetobjectFromJson<List<Products>>(HttpContext.Session, "cart");
        }

        public void OnPostCustom2()
        {
            if (_logger.Equals(null))
            {
                RedirectToPage("../Areas/Identity/Pages/Accounts/Register");
            }
            else
            {
                
            }
        }

        public IActionResult OnPostCust1(string myvalue)
        {
            if (User.Identity.IsAuthenticated)
            {
                if(myvalue == "Nike")
                {
                    return Redirect("../BrandsSort/Nike");
                }
                else if(myvalue == "Adidas")
                {
                    return Redirect("../BrandsSort/Adidas");
                }
                else if (myvalue == "Puma")
                {
                    return Redirect("../BrandsSort/Puma");
                }
                else if (myvalue == "UA")
                {
                    return Redirect("../BrandsSort/UnderArmour");
                }
                else if (myvalue == "NB")
                {
                    return Redirect("../BrandsSort/NewBalance");
                }
                else if (myvalue == "North")
                {
                    return Redirect("../BrandsSort/NorthFace");
                }
                else if (myvalue == "Reebok")
                {
                    return Redirect("../BrandsSort/Reebok");
                }
                else if (myvalue == "Vans")
                {
                    return Redirect("../BrandsSort/Reebok");
                }
                else if (myvalue == "Skechers")
                {
                    return Redirect("../BrandsSort/Skechers");
                }
                else
                {
                    return Page();
                }

            }
            else
            {
                return Redirect("Login");
            }
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Itec245_Final.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Thank.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Itec245_Final.Pages
{
    [Authorize(Roles = "User, Admin")]
    public class ThankModel : PageModel
    {
        public void OnGet()
        {
        }

        public void OnPostCust()
        {
            Response.Redirect("Index");
        }
    }
}

Pages/Checkout.cshtml
@page
@using Itec245_Final.Models
@using Microsoft.EntityFrameworkCore
@model Itec245_Final.Pages.CheckoutModel

@{
    ViewData["Title"] = "Checkout";
    HelperModel h = new HelperModel();
    var help = new HelperModel();
    var option = new DbContextOptionsBuilder<ApplicationDbContext>();
    option.UseSqlServer("Server=localhost;Database=MyshoppingCartDB;user id = sa;password = P@ssword!;encrypt=false;");
    var context = new ApplicationDbContext(option.Options);
    var cart = h.GroupItems(User.Identity.Name, context);
    int count = h.countcart(User.Identity.Name, context);
    decimal total = h.GetTotal(User.Identity.Name, context);
    string address = "";
    List<Shoes> Checkout = cart;

}

<body class="bg-light">

    <div class="container">

          <ul class="list-group mb-3">
                    <div class="container d-flex ">
                        <div class="row">
                    @if (cart != null && cart.Count > 0)
                            {
                        foreach (var item in cart)
                        {
                        <div class="card m-3" style="width: 18rem;">
                            <a href="@Html.DisplayFor(modelItem => item.Images)">
                                <img class="card card-img-top myimg" style="height:250px; margin-top:10px;" src="@Html.DisplayFor(modelItem => item.Images)" alt="Card image cap" onclick="myfunction()">
                            </a>
                            <div class="card-body">
                                <h5 class="text-black">@Html.DisplayFor(modelItem => item.Brand)</h5>
                                <p class="text-black">@Html.DisplayFor(modelItem => item.Name)</p>
                                <p class="text-black">@Html.DisplayFor(modelItem => item.Type)</p>
                                <p class="text-black">Price:  @Html.DisplayFor(modelItem => item.Price)</p>
                                <p class="text-black ">Quantity:  @Html.DisplayFor(modelItem => item.Quantity)</p>
                                <form method="post">
                                    <button class="btn btn-danger" asp-route-myvalue="@item.Id" asp-page-handler="RemoveCustom">-</button>
                                        <button class="btn btn-success" asp-route-myvalue="@item.Id" asp-page-handler="AddCustom">+</button>
                                </form>
                            </div>
                        </div>


                        }
                    }
                    else{

                        <h1 class="text-xl-center justify-content-center">Cart is Empty!</h1>
                    }
                    
                            
                   <br />
                   <br />
                   <br />
                   <br />
                   <br />
                    <h1>Total : $@total CAD</h1>
                            
                        </div>

                    </div>
          </ul>

          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code">
              <div class="input-group-append">
                <button type="submit" class="btn btn-secondary">Redeem</button>
              </div>
            </div>
          </form>
          <br />
          <br />
          <br />
          <br />
        </div>
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Billing address</h4>
          <form class="needs-validation" novalidate>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">First name</label>
                    <input type="text" class="form-control" id="firstName" placeholder="" value="@User.Identity.Name" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
            </div>

            

            <div class="mb-3">
              <label for="email">Email <span class="text-muted">(Optional)</span></label>
                <input type="email" class="form-control" id="email" placeholder="you@example.com" value="@User.Identity.Name">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="mb-3">
              <label for="address">Address</label>
              <input type="text"  class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="mb-3">
              <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="row">
              <div class="col-md-5 mb-3">
                <label for="country">Country</label>
                <select class="custom-select d-block w-100" id="country" required>
                  <option value="">Choose...</option>
                  <option>Canada</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-md-4 mb-3">
                <label for="state">State</label>
                <select class="custom-select d-block w-100" id="state" required>
                  <option value="">Choose...</option>
                  <option>Alberta</option>
                  <option>British Columbia</option>
                  <option>Ontario</option>
                  <option>Manitoba</option>
                  <option>Quebec</option>

                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="zip">Zip</label>
                <input type="text" class="form-control" id="zip" placeholder="" required>
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
            <hr class="mb-4">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="same-address">
              <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info">
              <label class="custom-control-label" for="save-info">Save this information for next time</label>
            </div>
            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>

            <div class="d-block my-3">
              <div class="custom-control custom-radio">
                <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                <label class="custom-control-label" for="credit">Credit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="debit">Debit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="paypal">Paypal</label>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="cc-name">Name on card</label>
                <input type="text" class="form-control" id="cc-name" placeholder="" required>
                <small class="text-muted">Full name as displayed on card</small>
                <div class="invalid-feedback">
                  Name on card is required
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="cc-number">Credit card number</label>
                <input type="text" class="form-control" id="cc-number" placeholder="" required>
                <div class="invalid-feedback">
                  Credit card number is required
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">Expiration</label>
                <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                <div class="invalid-feedback">
                  Expiration date required
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">CVV</label>
                <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                <div class="invalid-feedback">
                  Security code required
                </div>
              </div>
            </div>
            <hr class="mb-4">
        </form>
        @if(cart.Count > 0){
            <form method="post">
                <button class="btn btn-primary btn-lg btn-block" asp-page-handler="Final" type="submit">Continue to checkout</button>
            </form>
        }
        
            
          
        </div>
      </div>


    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<script src="~/js/hider.js"></script>
<link href="~/css/styles.css" rel="stylesheet" />
<style>
    body {
        background-color: black;

    }
</style>


</div>












<div id="carouselExample" class="carousel slide carousel-fade">

    <div class="carousel-inner">
        <div class="carousel-item active">
            <video class="d-block w-100" autoplay loop muted>
                <source src="~/Videos/shoe1.mp4" type="video/mp4" />
            </video>
           
        </div>
        <div class="carousel-item">
            <video class="d-block w-100" autoplay loop muted>
                <source src="~/Videos/shoe2.mp4" type="video/mp4" />
            </video>
           
        </div>
        <div class="carousel-item">
            <video class="d-block w-100" autoplay loop muted>
                <source src="~/Videos/Puma.mp4" type="video/mp4" />
            </video>
            
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<br />
<br />


<!-- Image Selector start -->

<section>
<div>
    <form method="post">
    <div class="d-flex">
        <div class="d-flex p-md-5">
            <button asp-page-handler="Cust1" asp-route-myvalue="Nike" class="bg-black rounded-circle ">
                        <img typr="submit" class="btn rounded-circle hovimg" style="width:150px; height:150px;" src="https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F67979fc2-9bc6-4ef1-a91a-9f8129c57645_1500x1500.jpeg" alt="">

                    </button>

        </div>

            <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="Adidas" class="bg-black rounded-circle ">
                <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://njmarlins.com/wp-content/uploads/sites/692/2015/04/adidas-logo.jpg" alt="">
                    </button>
         </div>

            <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="Puma" class="bg-black rounded-circle ">
                <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://assets.turbologo.com/blog/en/2019/11/19084917/puma-logo-cover.png" alt="">
                    </button>
            </div>

            <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="UA" class="bg-black rounded-circle ">
                <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://w0.peakpx.com/wallpaper/569/457/HD-wallpaper-under-armour-black-logo-tinku-bandito.jpg" alt="">
                    </button>
            </div>
                <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="NB" class="bg-black rounded-circle ">
                        <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://zeevector.com/wp-content/uploads/New-Balance-Logo-Black-and-White.png" alt="">
                    </button>
                </div>

                <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="Vans" class="bg-black rounded-circle ">
                        <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://i.pinimg.com/originals/ff/2c/c9/ff2cc9bdd6279c6531163189137a60a7.jpg" alt="">
                    </button>
                </div>
                <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="North" class="bg-black rounded-circle ">
                        <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://1000logos.net/wp-content/uploads/2017/05/Symbol-North-Face.jpg" alt="">
                    </button>
                </div>
                <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="Reebok" class="bg-black rounded-circle ">
                        <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/S/aplus-media-library-service-media/3b14cfb9-b10b-4215-af2b-acc5f0efd342.__CR0,0,1464,600_PT0_SX1464_V1___.jpg" alt="">
                    </button>
                </div>
                <div class="d-flex p-md-5">
                    <button asp-page-handler="Cust1" asp-route-myvalue="Skechers" class="bg-black rounded-circle ">
                        <img class="rounded-circle hovimg" style="width:150px; height:150px;" src="https://www.skechers.com/on/demandware.static/Sites-USSkechers-Site/-/default/images/skechers_logo.png" alt="">
                    </button>
                </div>

    </div>
        </form>
</div>
</section>



<!-- Image Selector End -->


    <!-- Subscribe Start -->
    <div class="container-fluid bg-dark my-5">
        <div class="row justify-content-md-center py-5 px-xl-5">
            <div class="col-md-6 col-12 py-5">
                <div class="text-center mb-2 pb-2">
                    <h2 class="section-title px-5 mb-3"><span class="bg-dark px-2">Stay Updated</span></h2>
                    <p id="next">Subscribe to Stay Updated</p>
                </div>
                <form method="post">
                    <div class="input-group" id="Sub">
                        <input type="email" id="mail" class="form-control border-white p-2" placeholder="Email Goes Here">
                        <div class="input-group-append">
                        <a class="btn button-cool" onclick="myFunction()"  style="--content:'SUBSCRIBE'; left:15px;">
                            <div class="left"></div>
                            SUBSCRIBE
                            <div class="right"></div>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>

Pages/Thank.cshtml
@page
@model Itec245_Final.Pages.ThankModel
@{
}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootstrap 5 Thank You Example</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="vh-100 d-flex justify-content-center align-items-center">
        <div>
            <div class="mb-4 text-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="text-success" width="75" height="75"
                     fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
                </svg>
            </div>
            <div class="text-center">
                <h1>Thank You !</h1>
                <p>Your Order is Confirmed</p>
                <form method="post">
                    <button class="btn btn-primary" asp-page-handler="Cust">Back Home</button>
                </form>
                
            </div>
        </div>
</body>